#!/bin/sh

for f in huawei_hilink huawei_sms read_sms delete_sms; do
    if [ ! -L /www/cgi-bin/$f ]; then
        ln -s /usr/share/huawei_hilink/$f /www/cgi-bin/$f
    fi
    sleep 1
done

chmod +x /usr/share/huawei_hilink/*
